### ISSUE TITLE
Error is raised after saving a model for the 994th time

### ISSUE THREAD

**Issue by adriaat** [adriaat/quantnn#3]
When executing the `save` method of a `QRNN` object the 994th time in my training scripts, the following error is raised
```
Traceback (most recent call last):
  File "/home/amell/iceseviri/trials/mlp_adam_constant_mse_zm.py", line 186, in <module>
    qrnn.save(os.path.join(parent_dir, '{:}_epoch{:}.pt'.format(ID, str(i+1).zfill(epochs_str_len))))
  File "/home/amell/quantnn/quantnn/neural_network_model.py", line 297, in save
    self.backend.save_model(file, self.model)
  File "/home/amell/quantnn/quantnn/models/pytorch/common.py", line 66, in save_model
    shutil.rmtree(path)
  File "/home/amell/miniconda3/envs/iceseviri/lib/python3.9/shutil.py", line 726, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/amell/miniconda3/envs/iceseviri/lib/python3.9/shutil.py", line 639, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/home/amell/miniconda3/envs/iceseviri/lib/python3.9/shutil.py", line 635, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
OSError: [Errno 24] Too many open files: '/tmp/tmp5rypoqy5'
```

However, I do not manage to reproduce this error when only loading a model and saving it many times, that is
```python
import quantnn

qrnn = quantnn.QRNN.load("/path/to/model.pt")

for i in range(10_000):
    qrnn.save("model_{:}.pt".format(str(i).zfill(5))
```
does not reproduce this error.

**Comment by adriaat** [comment]
A workaround is to increase the ulimit. My system's default is
```
$ ulimit -n
1024
````
but increasing it to 
```
$ ulimit -n 1000000
```
does not raise this error.

Note that this change in the ulimit is for each session, that is, before running the script in a session, the ulimit has to be previously updated for the session.
